name: Build packages and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup
        - /chip8/:/chip8
    steps:
      - name: Get chip8
        uses: actions/checkout@v2
        with:
          repository: 'legendary-cookie/chip8-pkgbuild'
          path: '/chip8'
        
      - name: Build chip8
        uses: FFY00/build-arch-package@v1
        with:
          PKGBUILD: /chip8/PKGBUILD

